cmake_minimum_required(VERSION 3.13)
set(CMAKE_VERBOSE_MAKEFILE on)
set(NATIVERENDER_ROOT_PATH ${CMAKE_CURRENT_SOURCE_DIR})
set(rnoh_rive_generated_dir "${CMAKE_CURRENT_SOURCE_DIR}/generated")
file(GLOB_RECURSE rnoh_rive_generated_SRC "${rnoh_rive_generated_dir}/**/*.cpp")
file(GLOB rnoh_rive_SRC CONFIGURE_DEPENDS *.cpp)
add_library(rnoh_rive SHARED ${rnoh_rive_generated_SRC} ${rnoh_rive_SRC})
target_include_directories(rnoh_rive PUBLIC ${CMAKE_CURRENT_SOURCE_DIR} ${rnoh_rive_generated_dir})
target_link_libraries(rnoh_rive PUBLIC rnoh)